site_name: Meu Glossário de Estudos
site_description: Um glossário pessoal para anotações e estudos
theme:
  name: material
  features:
    - search.suggest
    - search.highlight

nav:
  - Início: index.md
  - Arquitetura:
    - Visão Geral: arquitetura/index.md
  - Backend:
    - Visão Geral: backend/index.md
  - Conceitos Gerais:
    - Arquitetura: conceitos-gerais/index.md
  - Sobre: sobre.md
