site_name: Meu Glossário de Estudos
site_description: Um glossário pessoal para anotações e estudos
theme:
  name: material
  features:
    - search.suggest
    - search.highlight

nav:
  - Início: index.md
  - Arquitetura:
    - Visão Geral: arquitetura/index.md
  - Backend:
    - Visão Geral: backend/index.md
    - Hash: backend/hash.md
    - JVM: backend/jvm.md
    - Operadores: backend/operadores.md
    - Steams: backend/steams.md
  - Conceitos Gerais:
    - Visão Geral: conceitos-gerais/index.md
    - API: conceitos-gerais/api.md
    - Banco de Dados: conceitos-gerais/banco-de-dados.md
    - Memória: conceitos-gerais/memoria.md
  - Sobre: sobre.md
